module.exports = {
  pathPrefix: "/",
  title: `Country Barn Builders`,
  description: `Country Barn Builders is a full service portable storage shed company that specializes in standard and custom solutions for any budget. We service London, KY and the surrounding areas.`,
  url: "https://practical-mestorf-9c8a21.netlify.com",
  siteURL: "https://practical-mestorf-9c8a21.netlify.com/",
  siteLanguage: "en",
  logo: "/images/company-logo.png",
  banner: "/images/london-lot.jpg",
  favicon: "/images/favicon.png",
  shortName: "Country Barn",
  author: `Luke`,
  themeColor: `#F9F5E3`,
  backgroundColor: `#C6C2B1`,
  twitter: `@lqm_19`,
}
